version: "3.9"

services:
  postgresql:
    image: docker.io/postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=simplesedge
      - POSTGRES_PASSWORD=secret

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5

  feed:
    build:
      context: ./feed
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgresql:5432/simplesedge?sslmode=disable
    depends_on:
      - postgresql

  redis:
    image: docker.io/redis:7
    ports:
      - "6379:6379"
    # command: >
    #   --requirepass prediction

volumes:
  postgres_data:
    driver: local