# gen:
# 	rm -rf news_scraping/load/processing
# 	cd ../../../proto && make gen
# 	cp -Rv ../../../proto/gen/python/processing ./news_scraping/load/processing

# prep:
# 	poetry install
# 	cd ../../../proto && make gen && poetry build