// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Document struct {
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Site        string         `json:"site"`
	SiteFull    string         `json:"site_full"`
	SiteSection string         `json:"site_section"`
	Headline    string         `json:"headline"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	Ticker      sql.NullString `json:"ticker"`
	Tickers     []string       `json:"tickers"`
	PublishedAt time.Time      `json:"published_at"`
	Language    sql.NullString `json:"language"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Model struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Role        string         `json:"role"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type SentimentScore struct {
	ID           int64     `json:"id"`
	ModelID      int64     `json:"model_id"`
	DocumentGuid string    `json:"document_guid"`
	Sentiment    int64     `json:"sentiment"`
	Confidence   int64     `json:"confidence"`
	CreatedAt    time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiredAt    time.Time `json:"expired_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
