// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApiKey(ctx context.Context, apiKey string) (ApiKey, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (Model, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (SentimentScore, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteDocuemnt(ctx context.Context, guid string) error
	DeleteModel(ctx context.Context, id int64) error
	DeleteScore(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, email string) error
	DisableApiKey(ctx context.Context, apiKey string) (ApiKey, error)
	GetApiKey(ctx context.Context, apiKey string) (ApiKey, error)
	GetDocument(ctx context.Context, guid string) (Document, error)
	GetModel(ctx context.Context, id int64) (Model, error)
	GetScore(ctx context.Context, id int64) (SentimentScore, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error)
	ListScores(ctx context.Context, arg ListScoresParams) ([]SentimentScore, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateScore(ctx context.Context, arg UpdateScoreParams) (SentimentScore, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
