[tool.poetry]
name = "news-nlp"
version = "0.1.0"
description = ""
authors = ["jst2702 <jst2702@vt.edu>"]
readme = "README.md"
packages = [{include = "news_nlp"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
