# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processing/v1alpha1/document.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"processing/v1alpha1/document.proto\x12\nprocessing\"\xb8\x02\n\x08\x44ocument\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n\x04site\x18\x03 \x01(\tR\x04site\x12\x1c\n\tsite_full\x18\x04 \x01(\tR\tsite_full\x12\"\n\x0csite_section\x18\x05 \x01(\tR\x0csite_section\x12\x1a\n\x08headline\x18\x06 \x01(\tR\x08headline\x12\x14\n\x05title\x18\x07 \x01(\tR\x05title\x12\x12\n\x04\x62ody\x18\x08 \x01(\tR\x04\x62ody\x12\x16\n\x06ticker\x18\t \x01(\tR\x06ticker\x12\x18\n\x07tickers\x18\n \x03(\tR\x07tickers\x12\x1c\n\tpublished\x18\x0b \x01(\tR\tpublished\x12\x1a\n\x08language\x18\x0c \x01(\tR\x08languageBg\n\x0e\x63om.processingB\rDocumentProtoP\x01\xa2\x02\x03PXX\xaa\x02\nProcessing\xca\x02\nProcessing\xe2\x02\x16Processing\\GPBMetadata\xea\x02\nProcessingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing.v1alpha1.document_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.processingB\rDocumentProtoP\001\242\002\003PXX\252\002\nProcessing\312\002\nProcessing\342\002\026Processing\\GPBMetadata\352\002\nProcessing'
  _DOCUMENT._serialized_start=51
  _DOCUMENT._serialized_end=363
# @@protoc_insertion_point(module_scope)
