# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processing/v1alpha1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from processing.v1alpha1 import rpc_document_pb2 as processing_dot_v1alpha1_dot_rpc__document__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!processing/v1alpha1/service.proto\x12\nprocessing\x1a&processing/v1alpha1/rpc_document.proto\x1a\x1cgoogle/api/annotations.proto2\x95\x02\n\x10IngestionService\x12\x88\x01\n\x0eIngestDocument\x12!.processing.IngestDocumentRequest\x1a\".processing.IngestDocumentResponse\"/\x82\xd3\xe4\x93\x02)\"$/processing/v1alpha1/ingest_document:\x01*\x12v\n\rListDocuments\x12 .processing.ListDocumentsRequest\x1a!.processing.ListDocumentsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1alpha1/list_documentsBf\n\x0e\x63om.processingB\x0cServiceProtoP\x01\xa2\x02\x03PXX\xaa\x02\nProcessing\xca\x02\nProcessing\xe2\x02\x16Processing\\GPBMetadata\xea\x02\nProcessingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing.v1alpha1.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.processingB\014ServiceProtoP\001\242\002\003PXX\252\002\nProcessing\312\002\nProcessing\342\002\026Processing\\GPBMetadata\352\002\nProcessing'
  _INGESTIONSERVICE.methods_by_name['IngestDocument']._options = None
  _INGESTIONSERVICE.methods_by_name['IngestDocument']._serialized_options = b'\202\323\344\223\002)\"$/processing/v1alpha1/ingest_document:\001*'
  _INGESTIONSERVICE.methods_by_name['ListDocuments']._options = None
  _INGESTIONSERVICE.methods_by_name['ListDocuments']._serialized_options = b'\202\323\344\223\002\032\022\030/v1alpha1/list_documents'
  _INGESTIONSERVICE._serialized_start=120
  _INGESTIONSERVICE._serialized_end=397
# @@protoc_insertion_point(module_scope)
