# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apis.v1alpha1 import rpc_document_pb2 as apis_dot_v1alpha1_dot_rpc__document__pb2
from apis.v1alpha1 import rpc_user_pb2 as apis_dot_v1alpha1_dot_rpc__user__pb2


class SimpleSedgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/apis.SimpleSedge/CreateUser',
                request_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserResponse.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/apis.SimpleSedge/LoginUser',
                request_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/apis.SimpleSedge/UpdateUser',
                request_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserResponse.FromString,
                )
        self.VerifyEmail = channel.unary_unary(
                '/apis.SimpleSedge/VerifyEmail',
                request_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailResponse.FromString,
                )
        self.ListDocuments = channel.unary_unary(
                '/apis.SimpleSedge/ListDocuments',
                request_serializer=apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsResponse.FromString,
                )
        self.IngestDocument = channel.unary_unary(
                '/apis.SimpleSedge/IngestDocument',
                request_serializer=apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentRequest.SerializeToString,
                response_deserializer=apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentResponse.FromString,
                )


class SimpleSedgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Ingest a new data object for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleSedgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserResponse.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserResponse.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentRequest.FromString,
                    response_serializer=apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apis.SimpleSedge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleSedge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/CreateUser',
            apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__user__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/LoginUser',
            apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__user__pb2.LoginUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/UpdateUser',
            apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__user__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/VerifyEmail',
            apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__user__pb2.VerifyEmailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/ListDocuments',
            apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__document__pb2.ListDocumentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apis.SimpleSedge/IngestDocument',
            apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentRequest.SerializeToString,
            apis_dot_v1alpha1_dot_rpc__document__pb2.IngestDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
