# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apis/v1alpha1/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pis/v1alpha1/user.proto\x12\x04\x61pis\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n\x04User\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12J\n\x13password_changed_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x11passwordChangedAt\x12\x39\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtBE\n\x08\x63om.apisB\tUserProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x04\x41pis\xca\x02\x04\x41pis\xe2\x02\x10\x41pis\\GPBMetadata\xea\x02\x04\x41pisb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apis.v1alpha1.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010com.apisB\tUserProtoP\001\242\002\003AXX\252\002\004Apis\312\002\004Apis\342\002\020Apis\\GPBMetadata\352\002\004Apis'
  _USER._serialized_start=68
  _USER._serialized_end=259
# @@protoc_insertion_point(module_scope)
